imports:
    - { resource: parameters.yml, ignore_errors: true }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: defaults.ini }
    - { resource: ../../config/parameters.ini, ignore_errors: true}

    - { resource: ../../config/db.xml,    ignore_errors: false }
    - { resource: ../../config/cache.xml, ignore_errors: true }
    - { resource: ../../config/cdn.xml,   ignore_errors: true }
    - { resource: ../../config/mail.xml,  ignore_errors: true }
    - { resource: ../../config/queue.xml, ignore_errors: true }
parameters:
    knp_paginator.template.pagination: 'MopaBootstrapBundle:Pagination:sliding.html.twig'

framework:
    annotations:     ~
    secret:          %kernel.secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: %assets.version%
        assets_base_urls: %assets.base_urls%
    translator:
        fallback: %kernel.locale%
    default_locale: %kernel.locale%
    trusted_proxies: %kernel.trusted_proxies%
    session:
        name: "session"
        handler_id: zym_session.storage.handler.pdo
    fragments:   { path: /_fragment }
    esi:            true
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'MopaBootstrapBundle:Form:fields.html.twig'
    exception_controller: FOS\RestBundle\Controller\ExceptionController::showAction

# Assetic Configuration
assetic:
    debug: %kernel.debug%
    use_controller: false
    bundles: ['CmfCreateBundle']
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        less:
            node: %assetic.less.node_bin%
            node_paths: [%assetic.less.node_paths%]
        uglifycss: ~
        uglifyjs2: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %db.default.driver%
        host:     %db.default.host%
        dbname:   %db.default.dbname%
        user:     %db.default.user%
        password: %db.default.password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                auto_mapping: true
                connection: default
                mappings:
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                        alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_translator:
                        type: annotation
                        prefix: Gedmo\Translator\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                        alias: GedmoTranslator # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        alias: GedmoTree # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true

doctrine_phpcr:
    # Configure the PHPCR session
    session:
        backend:   %db.phpcr.backend%
        workspace: %db.phpcr.workspace%
        username:  %db.phpcr.user%
        password:  %db.phpcr.password%
    # Enable the ODM layer
    odm:
        auto_mapping: true
        auto_generate_proxy_classes: %kernel.debug%

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            tree: true
            timestampable: true
            translatable: true
            loggable: true
            sluggable: true
            softdeleteable: true

mopa_bootstrap:
    form:
        show_legend: false # default is true
        horizontal_label_class: col-lg-3 col-md-3
        horizontal_label_offset_class: col-lg-offset-3 col-md-offset-3
        horizontal_input_wrapper_class: col-lg-9 col-md-9

sensio_framework_extra:
    view:    { annotations: false }

# Swiftmailer Configuration
swiftmailer:
    transport:  %mail.transport%
#    encryption: %mail.encryption%
    auth_mode:  %mail.auth_mode%
    port:       %mail.port%
    host:       %mail.host%
    username:   %mail.username%
    password:   %mail.password%
    spool:     { type: memory }

knp_menu:
    templating: true
    twig: true

jms_security_extra:
    # Enabling this setting will add an additional special attribute "ROLE_IDDQD".
    # Anybody with this attribute will effectively bypass all security checks.
    enable_iddqd_attribute: false

    # Enables expression language
    expressions: false

jms_serializer:
    metadata:
        directories:
            FOSUserBundle:
                namespace_prefix: "FOS\\UserBundle"
                path: '@ZymUserBundle/Resources/config/serializer/fos-user-bundle'
            KnpPaginator:
                namespace_prefix: "Knp\\Component\\Pager"
                path: '@ZymPaginatorBundle/Resources/config/serializer/knp-components-pager'
            KnpPaginatorBundle:
                namespace_prefix: "Knp\\Bundle\\PaginatorBundle"
                path: '@ZymPaginatorBundle/Resources/config/serializer/knp-paginator-bundle'

liip_monitor:
    checks:
        disk_usage: ~
        php_extensions: [apc, curl, memcached, gd, imagick]
        writable_directory:
            - %kernel.root_dir%/../data/cache
            - %kernel.root_dir%/../data/indexes
            - %kernel.root_dir%/../data/logs
            - %kernel.root_dir%/../data/uploads

fos_js_routing:
    routes_to_expose:
        - 'fos_user_security_login'
        - 'fos_user_security_check'
        - 'fos_user_security_logout'
        - 'fos_user_registration_register'
        - 'fos_user_resetting_request'
        - 'fos_user_resetting_send_email'
        - 'fos_user_resetting_check_email'
        - 'fos_user_resetting_reset'

fos_rest:
    access_denied_listener:
        # all requests using the 'json' and 'xml' format will return a 403 on an access denied violation
        json: true
        xml: true
    allowed_methods_listener: true
    disable_csrf_role: ROLE_API
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    serializer:
        serialize_null: true
    view:
        serialize_null: true
        view_response_listener: true
        templating_formats:
            html: true
            ajax: true

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Zym\Bundle\UserBundle\Entity\User
    group:
        group_class: Zym\Bundle\UserBundle\Entity\Group
        group_manager: zym_user.group_manager.default
    service:
        user_manager: zym_user.user_manager.default

nelmio_api_doc: ~

opensky_runtime_config:
    provider: zym_runtime_config.provider
    cascade:  true

knp_gaufrette:

cmf_core:
    persistence:
        phpcr:
            enabled: true
            basepath: /cms
    publish_workflow:
        enabled: false

cmf_routing:
    chain:
        routers_by_id:
            cmf_routing.dynamic_router: 20
            router.default: 100
    dynamic:
        controllers_by_type:
            demo_type: sandbox_main.controller:typeAction
        controllers_by_class:
            Sandbox\MainBundle\Document\DemoClassContent: sandbox_main.controller:classAction
            Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\RedirectRoute:  cmf_routing.redirect_controller:redirectAction
            Symfony\Cmf\Bundle\BlogBundle\Document\Blog: cmf_blog.blog_controller:listAction
            Symfony\Cmf\Bundle\BlogBundle\Document\Post: cmf_blog.blog_controller:viewPostAction

        templates_by_class:
            Symfony\Cmf\Bundle\ContentBundle\Doctrine\Phpcr\StaticContent: SandboxMainBundle:StaticContent:index.html.twig
            Symfony\Cmf\Bundle\SimpleCmsBundle\Doctrine\Phpcr\Page:  ZymContentBundle:Pages:page.html.twig

cmf_simple_cms:
    persistence:
        phpcr:
            enabled: true
            basepath: /cms/content

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        #sonata.admin_doctrine_orm.block.audit:
        #    contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.rss:

        # Some specific block from the SonataMediaBundle
        #sonata.media.block.media:
        #sonata.media.block.gallery:
        #sonata.media.block.feature_media:

zym_media:
    db_driver: orm
    contexts:
        default:
            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
#    providers:
#        file:
#            filesystem: gaufrette.default_filesystem
#        image:
#            filesystem: gaufrette.default_filesystem
#        audio:
#            filesystem: gaufrette.default_filesystem
    cdn:
        server: ~

zym_user:
    db_driver: orm

zym_theme:
    theme_map:
        - { path: ^/, theme: zym3 }
        - { path: ^/admin, theme: zym3 }

zym_resque:
    redis:
        host: %queue.redis.host%                      # the redis host
        port: %queue.redis.port%                      # the redis port
        database: %queue.redis.database%              # the redis database

#zym_search_elastica:
#    clients:
#        default: { host: localhost, port: 9200 }
#    indexes:
#        test:
#            client: default

services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }