imports:
    - { resource: parameters.yml }

    - { resource: defaults.ini }
    - { resource: ../../config/parameters.ini, ignore_errors: true }
    - { resource: ../../config/db.xml, ignore_errors: false }
    - { resource: ../../config/mail.xml, ignore_errors: true }
    
    - { resource: security.yml }

parameters:
    knp_paginator.template.pagination: 'MopaBootstrapBundle:Pagination:sliding.html.twig'
            
framework:
    annotations:     ~
    secret:          %kernel.secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_parameters: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig', 'php'] } #assets_version: SomeVersionScheme
    translator:
        fallback: %kernel.locale%
    default_locale: %kernel.locale%
    trust_proxy_headers: false # Should Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:
        handler_id: zym_session.storage.handler.pdo
    esi:            true


# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'MopaBootstrapBundle:Form:fields.html.twig'
            
# Assetic Configuration
assetic:
    debug: %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        less:
            node: %assetic.less.node_bin%
            node_paths: [%assetic.less.node_paths%]
        yui_css:
            jar:  %assetic.yuicompressor.jar%
        yui_js:
            jar:  %assetic.yuicompressor.jar%

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %db.default.driver%
        host:     %db.default.host%
        dbname:   %db.default.dbname%
        user:     %db.default.user%
        password: %db.default.password%
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: false
        entity_managers:
            default:
                auto_mapping: true
                connection: default
                mappings:
                    StofDoctrineExtensionsBundle:
                        type:      xml
                        dir:       ./
                        prefix:    /
                        is_bundle: false

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            tree: true
            timestampable: true
            translatable: true
            loggable: true
            sluggable: true

mopa_bootstrap:
    form:
        show_legend: true # default is true

sensio_framework_extra: ~
            
# Swiftmailer Configuration
swiftmailer:
    transport: %mail.transport%
    host:      %mail.host%
    username:  %mail.username%
    password:  %mail.password%
    spool:     { type: memory }
    

knp_menu:
    templating: true
    twig: true

jms_security_extra:
    expressions: true

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Zym\Bundle\UserBundle\Entity\User
    group:
        group_class: Zym\Bundle\UserBundle\Entity\Group
        group_manager: zym_user.group_manager.default
    service:
        user_manager: zym_user.user_manager.default

zym_user:
    db_driver: orm

opensky_runtime_config:
    provider: zym_runtime_config.provider
    cascade:  true

services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    twig.extension.debug:
        class: Twig_Extensions_Extension_Debug
        tags:
            - { name: twig.extension }
