imports:
    - { resource: parameters.yml, ignore_errors: true }
    - { resource: security.yml }
    
    - { resource: defaults.ini }
    - { resource: ../../config/parameters.ini, ignore_errors: true}

    - { resource: ../../config/db.xml, ignore_errors: false }
    - { resource: ../../config/cache.xml, ignore_errors: true }
    - { resource: ../../config/cdn.xml, ignore_errors: true }
    - { resource: ../../config/mail.xml, ignore_errors: true }
    - { resource: ../../config/queue.xml, ignore_errors: true }

parameters:
    knp_paginator.template.pagination: 'MopaBootstrapBundle:Pagination:sliding.html.twig'

framework:
    annotations:     ~
    secret:          %kernel.secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig', 'php']
        assets_version: %assets.version%
        assets_base_urls: %assets.base_urls%
    translator:
        fallback: %kernel.locale%
    default_locale: %kernel.locale%
    trusted_proxies: %kernel.trusted_proxies%
    session:
        name: "session"
        handler_id: zym_session.storage.handler.pdo
    fragments:   { path: /_fragment }
    esi:            true
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'MopaBootstrapBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug: %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        less:
            node: %assetic.less.node_bin%
            node_paths: [%assetic.less.node_paths%]
        yui_css:
            jar:  %assetic.yuicompressor.jar%
        yui_js:
            jar:  %assetic.yuicompressor.jar%

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %db.default.driver%
        host:     %db.default.host%
        dbname:   %db.default.dbname%
        user:     %db.default.user%
        password: %db.default.password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%
    orm:
        auto_generate_proxy_classes: false
        entity_managers:
            default:
                auto_mapping: true
                connection: default

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            tree: true
            timestampable: true
            translatable: true
            loggable: true
            sluggable: true

mopa_bootstrap:
    form:
        show_legend: false # default is true

sensio_framework_extra: ~

# Swiftmailer Configuration
swiftmailer:
    transport:  %mail.transport%
#    encryption: %mail.encryption%
    auth_mode:  %mail.auth_mode%
    port:       %mail.port%
    host:       %mail.host%
    username:   %mail.username%
    password:   %mail.password%
    spool:     { type: memory }

knp_menu:
    templating: true
    twig: true

jms_security_extra:
    expressions: true

liip_monitor:
    checks:
        disc_usage: ~
        php_extensions: [apc, curl, memcached, gd, imagick]
        writable_directory:
          - %kernel.root_dir%/../data/cache
          - %kernel.root_dir%/../data/indexes
          - %kernel.root_dir%/../data/logs
          - %kernel.root_dir%/../data/uploads

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Zym\Bundle\UserBundle\Entity\User
    group:
        group_class: Zym\Bundle\UserBundle\Entity\Group
        group_manager: zym_user.group_manager.default
    service:
        user_manager: zym_user.user_manager.default

opensky_runtime_config:
    provider: zym_runtime_config.provider
    cascade:  true

knp_gaufrette:
    factories:
        zym_gaufrette: %kernel.root_dir%/../vendor/geoffreytran/zym/src/Zym/Bundle/GaufretteBundle/Resources/config/services.xml
    adapters:
        default:
            rackspace_cloudfiles:
                container: test
                user: rapp2012
                api_key: c361a08973e973c2da49c59379520dc7
    filesystems:
        default:
            adapter:    default

zym_media:
    db_driver: orm
    contexts:
        default:
            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
    providers:
        file:
            filesystem: gaufrette.default_filesystem
        image:
            filesystem: gaufrette.default_filesystem
            cdn: zym_media.cdn.rackspace_cloudfiles
    cdn:
        rackspace_cloudfiles:
            service_id: gaufrette.default_adapter.container

zym_user:
    db_driver: orm

zym_theme:
    theme_map:
        - { path: ^/, theme: zym3 }

zym_resque:
    redis:
        host: %queue.redis.host%                      # the redis host
        port: %queue.redis.port%                      # the redis port
        #database: %queue.redis.database%              # the redis database

#zym_search_elastica:
#    clients:
#        default: { host: localhost, port: 9200 }
#    indexes:
#        test:
#            client: default

services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    twig.extension.debug:
        class: Twig_Extensions_Extension_Debug
        tags:
            - { name: twig.extension }
