zym_content:
    resource: "@ZymContentBundle/Resources/config/routing.xml"
    prefix:   /admin/content

create:
    resource: "@CmfCreateBundle/Resources/config/routing/rest.xml"

create_image:
    resource: "@CmfCreateBundle/Resources/config/routing/image.xml"

PrestaSitemapBundle:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

LiipMonitorBundle:
    resource: "@LiipMonitorBundle/Resources/config/routing.yml"
    prefix: /monitor/health

zym_resque:
    resource: "@ZymResqueBundle/Resources/config/routing.xml"
    prefix: /admin/queue

zym_media:
    resource: "@ZymMediaBundle/Resources/config/routing/media.xml"
    prefix: /admin/media

zym_media_cdn:
    resource: "@ZymMediaBundle/Resources/config/routing/media_cdn.xml"
    prefix: /media

zym_field_fields:
    resource: "@ZymFieldBundle/Resources/config/routing/fields.xml"
    prefix:   /admin/structure/fields

zym_mail:
    resource: "@ZymMailBundle/Resources/config/routing/config.xml"
    prefix:   /admin/config/mail

zym_menu_menus:
    resource: "@ZymMenuBundle/Resources/config/routing/menus.xml"
    prefix:   /admin/structure/menus

zym_menu_categories:
    resource: "@ZymMenuBundle/Resources/config/routing/categories.xml"
    prefix:   /menu/categories

zym_router:
    resource: "@ZymRouterBundle/Resources/config/routing.xml"
    prefix:   /admin/config/routes

zym_security_access_rules:
    resource: "@ZymSecurityBundle/Resources/config/routing/access_rules.xml"
    prefix:   /admin/config/security/access-rules

zym_security_acl_roles:
    resource: "@ZymSecurityBundle/Resources/config/routing/acl_roles.xml"
    prefix:   /admin/config/security/roles

zym_security_acl_object_aces:
    resource: "@ZymSecurityBundle/Resources/config/routing/acl_object_aces.xml"
    prefix:   /admin/config/security/objects

zym_security_acl_entries:
    resource: "@ZymSecurityBundle/Resources/config/routing/acl_entries.xml"
    prefix:   /admin/config/security/entries

zym_node:
    resource: "@ZymNodeBundle/Resources/config/routing/nodes.xml"
    prefix:   /admin/content

zym_node_node_types:
    resource: "@ZymNodeBundle/Resources/config/routing/node_types.xml"
    prefix:   /admin/structure/content-types

zym_user_users:
    resource: "@ZymUserBundle/Resources/config/routing/users.xml"
    prefix:   /admin/users

zym_user_groups:
    resource: "@ZymUserBundle/Resources/config/routing/groups.xml"
    prefix:   /admin/groups

zym_user_resetting:
    resource: "@ZymUserBundle/Resources/config/routing/resetting.xml"
    prefix:   /account/forgot

zym_runtime_config_parameters:
    resource: "@ZymRuntimeConfigBundle/Resources/config/routing/parameters.xml"
    prefix:   /admin/config/parameters

zym_theme_theme_rules:
    resource: "@ZymThemeBundle/Resources/config/routing/theme_rules.xml"
    prefix:   /admin/structure/themes

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#fos_user_group:
#    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
#    prefix:   /groups

fos_user_registration:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix:   /register

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix:   /account/password