PrestaSitemapBundle:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

LiipMonitorBundle:
    resource: "@LiipMonitorBundle/Resources/config/routing.yml"
    prefix: /monitor/health

ZymResqueBundle:
    resource: "@ZymResqueBundle/Resources/config/routing.xml"
    prefix: /admin/queue

ZymMediaBundle:
    resource: "@ZymMediaBundle/Resources/config/routing/media.xml"
    prefix: /admin/media

ZymMediaBundleCDN:
    resource: "@ZymMediaBundle/Resources/config/routing/media_cdn.xml"
    prefix: /media

ZymFieldBundleFields:
    resource: "@ZymFieldBundle/Resources/config/routing/fields.xml"
    prefix:   /admin/structure/fields

ZymMailBundleConfig:
    resource: "@ZymMailBundle/Resources/config/routing/config.xml"
    prefix:   /admin/config/mail

ZymMenuBundleMenus:
    resource: "@ZymMenuBundle/Resources/config/routing/menus.xml"
    prefix:   /admin/structure/menus

ZymMenuBundleCategories:
    resource: "@ZymMenuBundle/Resources/config/routing/categories.xml"
    prefix:   /menu/categories

ZymRouterBundle:
    resource: "@ZymRouterBundle/Resources/config/routing.xml"
    prefix:   /admin/config/routes

ZymSecurityBundleAccessRules:
    resource: "@ZymSecurityBundle/Resources/config/routing/access_rules.xml"
    prefix:   /admin/config/security/access-rules

ZymSecurityBundleAclRoles:
    resource: "@ZymSecurityBundle/Resources/config/routing/acl_roles.xml"
    prefix:   /admin/config/security/roles

ZymSecurityBundleAclObjectAces:
    resource: "@ZymSecurityBundle/Resources/config/routing/acl_object_aces.xml"
    prefix:   /admin/config/security/objects

ZymSecurityBundleAclEntries:
    resource: "@ZymSecurityBundle/Resources/config/routing/acl_entries.xml"
    prefix:   /admin/config/security/entries

ZymNodeBundleNodeTypes:
    resource: "@ZymNodeBundle/Resources/config/routing/node_types.xml"
    prefix:   /admin/structure/content-types

ZymNodeBundleNodes:
    resource: "@ZymNodeBundle/Resources/config/routing/nodes.xml"
    prefix:   /admin/content

ZymUserBundleUsers:
    resource: "@ZymUserBundle/Resources/config/routing/users.xml"
    prefix:   /admin/users

ZymUserBundleGroups:
    resource: "@ZymUserBundle/Resources/config/routing/groups.xml"
    prefix:   /admin/groups

ZymRuntimeConfigBundleParameters:
    resource: "@ZymRuntimeConfigBundle/Resources/config/routing/parameters.xml"
    prefix:   /admin/config/parameters

ZymThemeBundleThemeRules:
    resource: "@ZymThemeBundle/Resources/config/routing/theme_rules.xml"
    prefix:   /admin/structure/themes

FOSUserBundleSecurity:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#FOSUserBundleGroups:
#    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
#    prefix:   /groups

FOSUserBundleRegistration:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix:   /register

FOSUserBundleResetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix:   /account/forgot

FOSUserBundleChangePassword:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix:   /account/password