security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface:        sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
#        in_memory:
#            memory: ~
#
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js|themes|scripts|styles)/
            security: false

        main:
            pattern: ^/.*
            form_login:
                check_path: fos_user_security_check
                login_path: fos_user_security_login
            logout:
                path: fos_user_security_logout
            anonymous: ~
            switch_user: ~
            remember_me:
                key: remember
                lifetime: 1209600


    access_control:
        - { path: ^/login,          roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register,       roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/account/forgot, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/admin, roles: ROLE_ADMIN }
#        - { path: ^/, roles: ROLE_USER }

        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }

    acl:
        connection: default
