#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'chef-client'

cookbook 'application'
cookbook 'application_php'
cookbook 'database'

cookbook 'apache2'
cookbook 'java'
cookbook 'php',
  :git => 'https://github.com/opscode-cookbooks/php'

cookbook 'mysql'
cookbook 'sqlite'

cookbook 'composer',
  :git => 'https://github.com/geoffreytran/chef-composer'

cookbook 'symfony2',
  :git => 'https://github.com/geoffreytran/chef-symfony2'

cookbook 'mysql_charset',
  :git => 'https://github.com/geoffreytran/chef-mysql_charset'

# Node.js
cookbook 'nodejs'
cookbook 'npm'

cookbook 'lesscss',
  :git => 'https://github.com/geoffreytran/chef-lesscss'

# Search
cookbook 'elasticsearch',
  :git => 'https://github.com/karmi/cookbook-elasticsearch'

# Caching
cookbook 'memcached'

# Queue
cookbook 'beanstalkd'

# Media
cookbook 'x264'
cookbook 'ffmpeg'
cookbook 'imagemagick'

# Version Control
cookbook 'git'
cookbook 'subversion'

# Utilities
cookbook 'apt'
cookbook 'yum'
cookbook 'screen'
cookbook 'htop'
cookbook 'rsync'
cookbook 'ark'
cookbook 'build-essential'
cookbook 'sudo'

cookbook 'users',
  :git => 'https://github.com/opscode-cookbooks/users'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
