#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'chef-client'
cookbook 'application',
  :git => 'https://github.com/opscode-cookbooks/application.git'

cookbook 'application_php'
cookbook 'database'

cookbook 'apache2'
cookbook 'java'

cookbook 'php54',
  :git => 'https://github.com/hairyhum/chef-php54.git'
cookbook 'php',
  :git => 'https://github.com/opscode-cookbooks/php'

cookbook 'mysql'
cookbook 'sqlite'

cookbook 'composer',
  :git => 'https://github.com/geoffreytran/chef-composer'

cookbook 'symfony2',
  :git => 'https://github.com/geoffreytran/chef-symfony2'

cookbook 'mysql_charset',
  :git => 'https://github.com/geoffreytran/chef-mysql_charset'

# Node.js
cookbook 'nodejs'
cookbook 'npm'

cookbook 'lesscss',
  :git => 'https://github.com/geoffreytran/chef-lesscss'

# Search
cookbook 'elasticsearch',
  :git => 'https://github.com/elasticsearch/cookbook-elasticsearch'

# Caching
cookbook 'memcached'

# Queue
cookbook 'redisio'

# Media
cookbook 'x264'
cookbook 'ffmpeg'
cookbook 'imagemagick'

# Version Control
cookbook 'git'
cookbook 'subversion'

# Process Management
cookbook 'supervisor'

# Utilities
cookbook 'apt', "1.7.0" # 1.7.0 requirement because Vagrant precise32 box is chef 10.14.x
cookbook 'yum'
cookbook 'cron'
cookbook 'screen'
cookbook 'htop'
cookbook 'rsync'
cookbook 'ark'
cookbook 'build-essential'
cookbook 'sudo'

cookbook 'users',
  :git => 'https://github.com/opscode-cookbooks/users'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'

#cookbook 'zym'
#  :git  => 'https://github.com/geoffreytran/symfony-zym',
#  :path => 'data/chef/site-cookbooks/zym'